import type { Metadata } from 'next';
import { Poppins, Roboto } from 'next/font/google';
import { ReactNode } from 'react';
import ThemeProvider from 'theme/ThemeProvider';
import './globals.css';

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
});

const roboto = Roboto({
    variable: '--font-roboto',
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'BlogMania',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
            <body>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
